### ISSUE TITLE
Python 3 conversion tracker

### ISSUE THREAD

**Issue by jeremycline** [fedora-infra/fmn#143]
This issue is meant to track issues concerning compatibility with Python 3. At the moment, no subpackages are known to be Python 3 compatible, so this issue can be easily divided into three subtasks:

- [ ] Convert fmn.rules subpackage to support Python 3

- [ ] Convert fmn.consumer subpackage to support Python 3

- [ ] Convert fmn.lib subpackage to support Python 3

This issue replaces https://github.com/fedora-infra/fmn.rules/issues/76 and https://github.com/fedora-infra/fmn.consumer/issues/95

**Comment by frenzymadness** [comment]
Hello.

I see that there is no progress with migration to Python 3, is it? I have a lot of experience with porting large codebases to support Python 2 and Python 3 at the same time so I might be able to help you.

Let me know if you want/need some help.

Have a nice day.
Lumír

**Comment by pypingou** [comment]
I wonder if at this point the idea isn't to re-write FMN entirely, porting it to fedora-messaging and python3, as well as fixing some more of the issues people have with the current UI/app all in one go :)

**Comment by ryanlerch** [comment]
The FMN rewrite is almost complete. This issue was reported against the old version of FMN, and likely does not apply anymore.

Closing, but reopen if you feel this still applies.
