### ISSUE TITLE
EPIC: Verify frontend <-> API compatibility

### ISSUE THREAD

**Issue by nphilipp** [fedora-infra/fmn#659]
# Story

As a user of FMN,
I want that the frontend and the API speak “the same language”,
so I don’t run into errors.

# Acceptance Criteria

- [ ] Frontend code is unit-tested (#715)
- [ ] Tests exist that verify that …
  - [ ] … endpoints called by the frontend exist in the API (path, HTTP method)
  - [ ] … data sent to the API is in an expected format
- [ ] JS/TS-side test fixtures verify that mocked return data conforms to the API spec.

# Background

This is an epic, each acceptance criterion should probably be implemented in one or more separate tasks (issues) – linked above – some of which could be explorative (“spikes”). Acceptance Criteria are listed in (assumed) order of increasing difficulty or effort to implement.

Suggested approach:

- Find a JS/TS package which can intercept API calls (like `responses` or `respx` in Python).
- Implement a JS/TS-side test fixture which mocks out calls to the real API backend during frontend tests. Needs to establish at which level mocking the calls is most practicable. Ensure this test fixture is applied to all JS/TS-side unit tests.
- When setting up tests, “pull” the OpenAPI spec from the API Python app, e.g. using this piece of Python code the `spec` variable contains a `dict` object which could be written out as JSON to be used JS/TS-side.

  ```
  from fmn.api import main
  spec = main.app.openapi()
  ```
- With this spec available, endpoint paths and format of data passed in or out can be verified.

**Comment by nphilipp** [comment]
Considered fixed by #752
